networks:
  default:
    external:
      name: int222-network
services:
  backend:
    container_name: backend_dev
    build: .
    image: ghcr.io/int222/backend:dev
    volumes:
      - ~/backend/dev/images:/src/images
